name: RestfulBooker API Tests

on:
  push:
    branches: [main]
  pull_request:

jobs:
  api-tests:
    runs-on: ubuntu-latest
    env:
      # Разрешаем использование Node 20 на раннере, чтобы избежать конфликтов в htmlextra
      ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Фиксируем стабильную 20 версию для Newman

      - name: Install Newman and htmlextra reporter
        run: npm install -g newman newman-reporter-htmlextra

      - name: Create output directory
        run: mkdir -p newman

      - name: Run Newman collection
        run: |
          newman run ://herokuapp.com.postman_collection.json \
            -e ://herokuapp.com.postman_environment.json \
            -r cli,htmlextra \
            --suppress-exit-code \
            --reporter-htmlextra-export newman/report.html \
            --reporter-htmlextra-omitHeaders \
            --reporter-htmlextra-omitRequestBodies \
            --reporter-htmlextra-omitResponseBodies \
            --env-var "base_url=https://://herokuapp.com/" \
            --env-var "valid_login=${{ secrets.API_USERNAME }}" \
            --env-var "valid_password=${{ secrets.API_PASSWORD }}"

      - name: Upload HTML Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: postman-api-test-report
          path: newman/report.html
