name: RestfulBooker API Tests

on:
  push:
    branches: [main]
  pull_request:

jobs:
  api-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Newman collection
        uses: postman/newman@v6
        with:
          collection: restful-booker.herokuapp.com.postman_collection.json
          environment: restful-booker.herokuapp.com.postman_environment.json
          env-var: |
            base_url=https://restful-booker.herokuapp.com/
            valid_login=${{ secrets.API_USERNAME }}
            valid_password=${{ secrets.API_PASSWORD }}
          reporters: cli